[workspace]
members = [
	"count_vowels",
	"reflect",
	"store_credit",
  "loop_forever",
  "count_vowels_kvstore",
]
resolver = "2"

[workspace.dependencies]
extism-pdk = {git = "https://github.com/extism/rust-pdk"}
anyhow = "1.0.75"
serde = "1.0.188"

