[package]
name = "reflect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace = true}
extism-pdk = {workspace = true}
serde = {workspace = true}

[lib]
crate_type = ["cdylib"]
